Update Wire.cpp
"Fix Wire.setClock() link error - remove reference to undefined current_speed"

While testing an SSD1306 OLED display using I2C on the MAX32630FTHR with the Maxim Arduino core version 1.1.5, I encountered a linker error related to TwoWire::setClock().

The error is:
TwoWire::setClock(unsigned long)': /.arduino15/packages/Maxim/hardware/arm/1.1.5/libraries/Wire/src/Wire.cpp:119: undefined reference to current_speed'`

The relevant code in:

~/.arduino15/packages/Maxim/hardware/arm/1.1.5/libraries/Wire/src/Wire.cpp

contains the following line near the end of setClock():

current_speed = speed; 

If I comment out this line:

// current_speed = speed; 

the project compiles successfully and the SSD1306 OLED display works correctly over I2C.

Question

Could you please confirm whether current_speed = speed; is expected to be present in TwoWire::setClock()?

If it is required, could the definition/declaration of current_speed be corrected so that the code links successfully?

If it is not required for the MAX32630FTHR implementation, should this line be removed or handled differently?

Environment
Board: MAX32630FTHR
Arduino IDE: 1.8.19
Maxim Arduino core: 1.1.5
Library: Wire
Peripheral: SSD1306 OLED via I2C
OS: Linux
Workaround: OLED works after commenting out current_speed = speed;

For now, commenting out the following line allows the application to compile and the OLED to operate: